### ISSUE TITLE
404 => http://mdp.github.io/gibberish-aes/gibberish-aes-test.html

### ISSUE THREAD

**Issue by alexparker** [mdp/gibberish-aes#16]
This link is broken. as `"Click here" to run the test package in your browser.` Thought you might like to know.

**Comment by CoolOppo** [comment]
paging @mdp

**Comment by mdp** [comment]
Sorry for the 2 year delay :) - Fixed!

**Comment by alexparker** [comment]
Ok, now i can get started...
