### ISSUE TITLE
Ongoing development — Planning

### ISSUE THREAD

**Issue by KenanSulayman** [mdp/gibberish-aes#22]
In order to keep this library attractive compared to solutions like [SJCL](https://github.com/bitwiseshiftleft/sjcl) we need to spot weaknesses create an outlook for the further development and maintenance.

That is, I divided this issue into multiple parts: 1. issues and weaknesses of this library as-is right now, 2. what needs to be done to resolve these issues and lastly, 3. general notes.

Let's see this as a „scrum“ in open-source spirit :v: 

### ⇝ Issues
 - No authentication before decrypting messages
 - Bad block method compared to SJCL

### ↯ Outlook

 - Implement message authentication
 - Revise block method

 - Refactor; break the library down to edible bits
 - Use native methods when used in server environments (Node)
 - Use ArrayBuffers et al

 - Spot potential weaknesses

### ↺ Notes
 - Lets see how SJCL is tackling the issues proposed by @mdp 
 - SJCL's AES effectively boils down to http://cl.ly/text/04440e0y0T1t/sjcl.js

**Comment by ivantcholakov** [comment]
SJCL is like a Swiss army knife - many choices are given. I like the approach of picking just one kind of encryption and keeping the API simple. I suppose that a new encryption is going to be picked up, but the current one should be kept for backward compatibility.

1.
There is what to be checked: How random is Math.random on different platforms, see the method randArr(num).

2. The method openSSLKey(passwordArr, saltArr) implements a standard routine, but it is old. Pass-phrase to key conversion relies on MD5 hashing, if it is possible, different OpenSSL hashing implementation has to be chosen.

**Comment by ivantcholakov** [comment]
https://twitter.com/ircmaxell/status/588770036162015232

**Comment by mdp** [comment]
While SJCL is a bit of a Swiss army knife, it's got a really simple API for new users and it's frequently updated. It's nearly a drop in replacement for Gibberish:

    sjcl.encrypt("password", "data")
    sjcl.decrypt("password", "encrypted-data")

It's using a authenticated AES algo, along with PBKDF2 hardening (not amazing, but better than nothing).

The other alternative is LibSodium, but I'm afraid that the JS port is still a bit of a nightmare to include in a large project in a sane way. I was able to create an example of how to match the simple Gibberish API in about < 30 lines of code though: https://github.com/mdp/gibberish-libsodium/blob/master/index.js

The alternatives are not perfect, but they are far superior to what Gibberish is using currently, and I don't have the time to update this library to the level required today.

**Comment by mdp** [comment]
I've update the Readme with a deprecation notice.

I'm happy to point people at an updated version of Gibberish if someone wants to fork it and continue development, but for now I think it's best to point potential users at more up to date libraries.

Thanks to everyone that helped out with this project.

**Comment by circlecycle** [comment]
I want to thank you again for your support. 

The research I did making http://tagos.io could not exist without out - although I will look into SJCL as a port. I made an aes/rsa identity library (locally, anyway, for the purpose of creating that site) and i will report back on whether it was “drop in” or what else I may’ve had to do. 

Thanks, again!
