### ISSUE TITLE
have any support for android and ios?

### ISSUE THREAD

**Issue by FMStephen** [mdp/gibberish-aes#25]
hellow, I want to user this aes method for my android app but I dont know how to make it. Holp for ur help

**Comment by mdp** [comment]
Gibberish AES is deprecated and I suggest a more up to date solution like Libsodium or NaCl.

Take a look at the bindings here: https://download.libsodium.org/doc/bindings_for_other_languages/index.html

Libsodium has support for Android and iOS as well.

Hope this helps.

**Comment by FMStephen** [comment]
thx alot :)

**Comment by KenanSulayman** [comment]
I suggest using libsodium. It's fast and we're deploying it everywhere. I can recommend the emscripten compiled version (if you're looking for a javascript version on a website et al.): https://github.com/jedisct1/libsodium.js - beware though that the API differs from each library using libsodium..

**Comment by FMStephen** [comment]
great help! thank u, let me check it out.
