### ISSUE TITLE
Symantec Endpoint Protection (SEP) Deleting gibberish-aes

### ISSUE THREAD

**Issue by udarr** [mdp/gibberish-aes#27]
I had Symantec Endpoint Protection (SEP) and it would find this minified gibberish-aes file in the project and delete it. Is there a reason why its doing that? I deleted Symantec and intend on replacing it with something else. However, this may not be a solution for lot of others who are using gibberish-aes

**Comment by wcalderw** [comment]
I've been working with my IT department on this. Other anti-virus packages (Kaspersky, Web Root, etc... ) don't seem to have this problem. Our current suspicion is that it's the Symantec virus definition library had a mistake in it. The latest symantec library update doesn't seem to have this issue anymore...

**Comment by mdp** [comment]
Not sure what could be triggering it. Happy to try and fix this if you find a specific cause. Closing for now, feel free to reopen. Thanks
