### ISSUE TITLE
Can not import as an `npm package`

### ISSUE THREAD

**Issue by mimoning** [mdp/gibberish-aes#29]
I install with npm module, I can't easy import it as an `npm package`

**Comment by khanhnb** [comment]
[Adding main fill](https://github.com/mdp/gibberish-aes/pull/26) should fix this problem.

**Comment by mdp** [comment]
This library was deprecated in 2014, and I'm not doing any updates to it anymore. In encryption terms, it's ancient and there are much better alternatives available out there (listed on the README). Of course, you're free to fork and update as you see fit, but please be aware that's it's using a very old AES mode. Thanks
